### ISSUE TITLE
Add Humanize Midi tracks feature

### ISSUE THREAD

**Issue by jjazzboss** [jjazzboss/JJazzLab#172]
Produced Midi tracks could be "humanized" by adjusting notes velocities & positions, probably with a specific approach per instrument. Priority #1  is drums+bass. Good candidate for a plugin.

If someone know good pointers on how to do this (beyond adding a slight randomization), that would help a lot. Ideally with open-sourced code...

**Comment by bdutta** [comment]
AFAIK almost most implementations of humanize only add slight randomization on various qualities -- timing, velocity especially for MIDI data, and in rare cases pitch (I suppose using pitch-bend). Agree completely on priority being drums and bass.
Perhaps a look at the Reaper humanize functions as JS plugins might be a good source of inspiration (as mentioned here: https://www.kvraudio.com/forum/viewtopic.php?f=6&t=A)
