### ISSUE TITLE
MacOS app can't access user folders

### ISSUE THREAD

**Issue by maedoc** [jjazzboss/JJazzLab#323]
(thanks for this app!)

I just downloaded v3.2.1 and it sounds great, but macOS recently introduced a thing where when an app tries to access e.g. ~/Downloads, a pop up notification requests approval from user.  This doesn't seem to happen with this app, and the folder is empty.  So I downloaded the sound fonts and then moved to my user home folder, and similarly I can't svae song files to my documents folder. 

I can take a look at why it happens, but wanted to note it here.

**Comment by jjazzboss** [comment]
Sorry I don't understand well the issue (and I don't have a Mac to test...) . You mean you can't save a song from JJazzLab ?

**Comment by maedoc** [comment]
I mean that JJazzLab doesn't have access to common folders.  Here's a screenshot for example of what I see when I try to open something I've downloaded:
<img width="706" alt="image" src="https://user-images.githubusercontent.com/5189886/190964970-99ac7e1a-eb83-42bd-abf7-cdd6eb4f0f69.png">
I'd expect not to see all the files, but the folders my downloads doesn't show up.  The initial problem was with the soundfont file, to be downloaded during installation: I downloaded but couldn't see it in the downloads folder, so I moved it to the home folder, at which point I could see the file in JJazzLab. 

Oddly enough I can access the $HOME/JJazzLab folder and its songs.  I tried symbolically linking a folder into $HOME and then JJazzLab can navigate into the folder but contents are still hidden. 

I've checked the help page from apple [here](https://support.apple.com/en-gb/guide/mac-help/mchld5a35146/mac) but I don't see anything unchecked.  I'll keep looking later.  I'm sure it's related to the security/privacy changes in the recent macOS versions; I'm on Monterey (12.5)

**Comment by jjazzboss** [comment]
Ok I understand now thanks. But not sure what I can do... I just use the standard Java open file dialogs.

**Comment by maedoc** [comment]
Seems since Catalina, https://support.apple.com/en-gb/guide/mac-help/mchld5a35146/10.15/mac/10.15

Is the mac app compiled with a recent version of the JVM?  If the JVM version is older than Catalina, it probably doesn't support this.

**Comment by jjazzboss** [comment]
The latest JJazzLab version (3.2.1) is built with JDK17 from Adoptium (released in 2021). But can you check in the JJazzLab Help/About window the exact JDK version ?   Some Linux users installed JJazzLab from third-party distributions which happened to not use the bundled JDK17...
