### ISSUE TITLE
Problem reading style (can't find the 'CASM' string at expected position)

### ISSUE THREAD

**Issue by bengan** [jjazzboss/JJazzLab#363]
Some examples:

INFO [YamahaRhythmProvider]: readFast() Reading /home/bengan/JJazzLab/Rhythms/ML2/September.sty
WARNING [YamahaRhythmProvider]: getFileRhythms() ex=Problem reading file /home/bengan/JJazzLab/Rhythms/ML2/September.sty. Ex=September.sty - read() can't find the 'CASM' string at expected position

INFO [YamahaRhythmProvider]: readFast() Reading /home/bengan/JJazzLab/Rhythms/ML2/Samba Pa Ti.sty
WARNING [YamahaRhythmProvider]: getFileRhythms() ex=Problem reading file /home/bengan/JJazzLab/Rhythms/ML2/Samba Pa Ti.sty. Ex=Samba Pa Ti.sty - read() can't find the 'CASM' string at expected position

I found the styles here:
https://psrtutorial.com/perf/juulML.html

It's the file ML2. Some of the sty-files have the same problem and some is ok.

My system:

>Log Session: Wednesday, June 21, 2023 at 2:20:14 PM Central European Summer Time
>System Info: 
  Product Version         = JJazzLab 13-00d6d969bf4d9b14e7406c9ee9cc13a61dc39655
  Operating System        = Linux version 6.3.6-1-default running on amd64
  Java; VM; Vendor        = 17.0.2; OpenJDK 64-Bit Server VM 17.0.2+8; Eclipse Adoptium
  Runtime                 = OpenJDK Runtime Environment 17.0.2+8

**Comment by jjazzboss** [comment]
File might be corrupted... Can you test the file on a Yamaha arranger ? Or can it be loaded by another software ?

**Comment by bengan** [comment]
Sorry. Don't have an Yamaha arranger, and the OS/software is Linux on my laptop and in the studio. But I did test to just rename the file to a midi (*.mid) file and import them to Qtractor and Ardour. Both could open the file and can play it.

**Comment by jjazzboss** [comment]
The error is in the non-Midi data of the Midi file, that's why file still can be opened by a Midi editor. Hence the file load test should be performed on a Yamaha arranger keyboard or "official" software.
