### ISSUE TITLE
Run on Ubuntu 22.04

### ISSUE THREAD

**Issue by antonio-petricca** [jjazzboss/JJazzLab#379]
I compiled it by Java 17, but running `JJazzLab/application/target/jjazzlab/bin/jjazzlab` I get the following error:

```
Unrecognized option: --add-modules=jdk.incubator.foreign
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by jjazzboss** [comment]
it's because jjazzlab is not run with JRE17, but probably an earlier JRE. You need to update `JJazzLab/application/target/jjazzlab/etc/jjazzlab.conf` file

**Comment by antonio-petricca** [comment]
Thank you it worked by changed the JDK home setting.

**Comment by wvengen** [comment]
#369 shows Java 17, now it compiles and runs.
