### ISSUE TITLE
Songs not saving properly

### ISSUE THREAD

**Issue by mcdoogs** [jjazzboss/JJazzLab#380]
New installation here. When I attempt to save a song, an error gets silently thrown and the new .sng file ends up mostly empty. I've tried a few different songs & restarting the program, it always seems to cut them off after line 9 - for example:

```
<Song resolves-to="org.jjazz.song.api.Song$SerializationProxy">
  <spVERSION>2</spVERSION>
  <spName>NewSong1</spName>
  <spComments>Edit me...</spComments>
  <spTempo>66</spTempo>
  <spClientProperties>
    <property name="PropCompactViewModeVisibleRps_16BeatBallad2.S014.prs-ID" value="rpVariationID,rpIntensityID,RpFillID"/>
    <property name="PropSsEditorZoomFactorX" value="100"/>
    <property name="SectionDisplayQuantization-A*4/4" value="ONE_QUARTER_BEAT"/>
```

A full debug log from a test session is attached. For that session, I started the program, added a few chords, then hit 'Save All', and attempted to save to the 'test1.sng' file above. Those `ExceptionInInitializerError` lines show up when attempting to save.

The 'Select Options to Export' dialog box also seems to get stuck on 'Loading...' forever - maybe the same root cause, if it's attempting to access some broken client setting?

It looks like the log has all the relevant system/Java details but let me know if I can provide any more info or test anything.
[error.log](https://github.com/jjazzboss/JJazzLab/files/13694616/error.log)

**Comment by jjazzboss** [comment]
it's because Java version is wrong and some java parameters are missing. How did you install it ? Seems to be a third-party package...
Safest: use v3.2.1 .zip file from jjazzlab.com. It is self sufficient. 
You can also try a 4.0 beta here. https://jjazzlab.freeforums.net/thread/524/jjazzlab-beta1-available-testing-linux

**Comment by mcdoogs** [comment]
Ahh, thanks. I remember now, I had installed the correct Java version manually, but last month Arch changed how they packaged the JRE & JDK and it was fastest to do a fresh reinstall of all Java packages, so I just have the latest version from Arch's repositories. I might try out the beta later, thanks.

**Comment by mcdoogs** [comment]
Oh, and I installed jjazzlab from the AUR: https://aur.archlinux.org/packages/jjazzlab-x-bin
