### ISSUE TITLE
"Linux Installation" description typing error

### ISSUE THREAD

**Issue by Nioubi24** [jjazzboss/JJazzLab#393]
Thanks very much for all your work..., nice tool!

Some little inconsistencies on the [https://www.jjazzlab.com/en/download/](url) page for the v2 Linux installation...

> Linux Ubuntu/Debian family (x64)
> 
> Download the .deb file and install it as shown below.
> 
> [jjazzlab_4.0.1-1_amd64.deb](https://www.jjazzlab.com/pkg/jjazzlab_4.0.1-1_amd64.deb)    md5sum: 1d5d96c0dcafe97a46b2fee07906a87b
> 
> sudo apt-get install ./JJazzLab-4.0.1-linux-x64.deb    # this will also download and install libfluidsynth if required

The .deb file is "**jj**azzla**b_4.0.1-1_amd**64.deb", but the command line specifies "**JJ**azzLa**b-4.0.1-linux-x**64.deb" :
- 1) Case sensitive ==> "jj" for the package and "JJ" for the command line
- 2) Versionning inconsistency ==> "4.0.1-1" for the package and "4.0.1" for the command line
- 3) Processor type ==> "amd64" for the package and "x64" for the command line
- 4) Inconsistencies between "-" and "_" in the name of the package and command line (before and after the version number)
- 5) You can specify that the command line must be run from the download directory

Have a nice New Year's Eve ;-D

**Comment by jjazzboss** [comment]
thanks, fixed.
