### ISSUE TITLE
New chord types

### ISSUE THREAD

**Issue by init-random** [jjazzboss/JJazzLab#416]
Hello -- How do you add a new chord type? For example Cm#7 [C, Eb, G, B]. This can be done as Eb+/C, but I cannot create an (Cm#7) alias for slash chords. Adding new chord types would also be helpful for chords stacked in fifths (C G D A), fourths, or seconds.

Second question, can we specify inversions? For example, Bb7 (dom7) third inversion is equivalent to Bb/Ab. Is there a way to specify this like "Bb7 III"? Consider a C chord with a G in the bass. Would this just be written C/G in JJazzLab?

Thank you!

**Comment by jjazzboss** [comment]
Please use the [JJazzLab forum](https://jjazzlab.freeforums.net/) for usage questions.  GitHub issues are only for bug reports or new feature requests.
