### ISSUE TITLE
Getting Fluidsynth to work on Linux

### ISSUE THREAD

**Issue by wvengen** [jjazzboss/JJazzLab#417]
Hi, first of all thanks for this great program!
I'm trying to get it running from source ([242e085](https://github.com/jjazzboss/JJazzLab/commit/242e0855fab432ef0c273e4e604f67b4b1ed456e)), and that seemed to work when using OpenJDK 17. But on start it complains that Fluidsynth is not available, in this case the cause is that no soundfont is set.

From the logs:
```
INFO [JJazzMidiSystem]: JJazzMidiSystem() Midi out devices=[]
INFO [JJazzMidiSystem]: setDefaultOutDevice() oldDevice=null newDevice=Java Synth (Gervill)
INFO [FluidSynthJava]: open() FluidSynth version=2.2.5
INFO [FluidSynthJava]: open() Native FluidSynth instance initialized
INFO [FluidSynthJava]: close() Native FluidSynth instance closed
WARNING [StartupEmbeddedSynthInitTask]: run() Can't activate embedded synth: Invalid SoundFont file null
```

In the UI I cannot find a way to set the soundfont. The gears icon for Fluidsynth is only pressable when Fluidsynth is enabled, but that isn't attainable because of the above error.

Is there supposed to be a default soundfont and/or a way to set the soundfont file manually?

**Comment by jjazzboss** [comment]
Download https://musical-artifacts.com/artifacts/1036 and copy it here: https://github.com/jjazzboss/JJazzLab/tree/master/modules/FluidSynthEmbeddedSynth/src/main/soundfont, rebuild JJazzLab.

**Comment by wvengen** [comment]
Ah, thank you so much!
