### ISSUE TITLE
Define desktop file categories

### ISSUE THREAD

**Issue by wvengen** [jjazzboss/JJazzLab#453]
From https://github.com/flathub/org.jjazzlab.JJazzLab/issues/3:
> Please define a proper category from https://specifications.freedesktop.org/menu-spec/latest/apa.html
> 
> https://raw.githubusercontent.com/jjazzboss/JJazzLab/bbd6ee18eeb55be3b002492cb70ba7487bfa427a/misc/org.jjazzlab.JJazzLab.desktop has no categories

[Flathub on categories and keywords](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#categories-and-keywords)
[Freedesktop on categories](https://specifications.freedesktop.org/menu-spec/latest/apa.html)

**Comment by wvengen** [comment]
Main category: Audio
Secondary category: Midi (even though on my system I have not yet been able to get Midi working with Flatpak, still is a midi app.)
Secondary category: Sequencer - _yes or no?_ (I would be careful and not include it, as its main task is not a sequencer.)
Secondary category: Music

**Comment by jjazzboss** [comment]
I'm confused, the missing categories are to be added in the .dekstop files ? From the documentation links I thought it was for the metainfo file... ?

**Comment by wvengen** [comment]
The _Launchable_ is a desktop file, which is used in desktop launchers etc.
I read that the metainfo file overrides the desktop file (so _maybe_ we don't need it there, not fully sure).

**Comment by wvengen** [comment]
Let's add the following line to the desktop file:
```
Categories=AudioVideo;Audio;Midi;Music;
```
That should be enough.
