### ISSUE TITLE
Add release to metainfo file

### ISSUE THREAD

**Issue by wvengen** [jjazzboss/JJazzLab#454]
Great to see a new release, thank you!

To be able to show this properly in app stores, including releasing an update for Flathub, the [metainfo file](https://github.com/jjazzboss/JJazzLab/blob/master/misc/org.jjazzlab.JJazzLab.metainfo.xml) needs to be updated with a new release.

Ideally, this would happen with the version tag, so that the source tarball contains the updated metainfo file, but for Flathub we can get away now with just updating the file without doing a new release.

**Comment by wvengen** [comment]
Super, thank you!

**Comment by wvengen** [comment]
Oops, the new version needs to be on top of the release list, or Flathub validation fails. I just found out, sorry. Could you correct it? Then I'll release 4.0.2 on Flathub.

**Comment by jjazzboss** [comment]
ok, it will be corrected for 4.1.1, which should be released this week.
