### ISSUE TITLE
EXE was still running after crash

### ISSUE THREAD

**Issue by jazi4** [jjazzboss/JJazzLab#460]
App(v4.1 and Windows10)  crashed but the EXE was still running and I was unable to terminate it with  any of the usual methods.
Unable to start another instance.
Had to reboot to get rid of it.
Is there some way that you can force the App to be terminated without a reboot?

**Comment by jazi4** [comment]
BUMP.
Please could someone respond?

**Comment by jjazzboss** [comment]
> Is there some way that you can force the App to be terminated without a reboot?
No idea...

Do you have the log when it crashed ?
