### ISSUE TITLE
Doesn't startup properly the second time 

### ISSUE THREAD

**Issue by vlappa** [jjazzboss/JJazzLab#497]
Now jjazzlab doesn't start up properly the second time until I remove the ~/.jjazzlab folder on Linux.  I've set it to use VirMidi. Probably something with the extra donation window? Does it spoil the fun?

```
$jjazzlab
WARNING: Using incubator modules: jdk.incubator.foreign
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/opt/jjazzlab/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
```

**Comment by jjazzboss** [comment]
everything normal in the log. Try to get the log when you get the grey screen.

**Comment by vlappa** [comment]
This is when I get the grey screen

[messages.log](https://github.com/user-attachments/files/17781984/messages.log)

**Comment by jjazzboss** [comment]
So it seems the error comes from out of jjazzlabLe 15 nov. 2024 à 23:24, vlappa ***@***.***> a écrit :﻿
This is when I get the grey screen
messages.log

**Comment by vlappa** [comment]
Or jjazlab doesn't produce log messages when it goes wrong.   
Or jjazzlab can't handle the outside world in this case (virmidi) after restart, cause the virmidi works fine in jjazzlab before restart. 

jjazzlab is not able to restore the state which worked perfectly fine, before quit.

**Comment by vlappa** [comment]
Would it be helpful to upload some config files?

**Comment by jjazzboss** [comment]
I don't understand, it's the first time I hear about this issue. 

Does the problem always happen as soon as you select virMidi ? Or the first time you select virMidi it works, then you quit JJazzLab, restart and now it fails ? If it's the second option, maybe virMidi is not closed cleanly when JJazzLab is shutdown...

When you select a Midi out device in JJazzLab, JJazzLab just opens it using standard Java API (https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/javax/sound/midi/MidiDevice.html#open()). MidiUnavailableExceptions are caught by JJazzLab. If there was a SecurityException you should have seen it in the log. After opening the device, JJazzLab does nothing on the device except sending Midi messages for playing music...

**Comment by vlappa** [comment]
I think it is the desktop environment. With DWM, I get a grey unresponsive window on the second launch. It seems to work in LXDE.
